# -*- encoding: utf-8 -*-

{
    'name': 'GST EwayBill',
    'version': '13.0.0.1',
    'category': 'Integration',
    'summary': """
        module to allow Eway Bill integration with Taxpro
        Documentation,eway,E-way,e-waybill,ebill,eway bill,e-way bill,eway,Eway bill, eway-bill, e-bill,gstewaybill,gst eway bill,gst_eway_bill,eway bill, gst,gst bill, gst_eway,GST EWAY BILL,
        Generate E-invoice, E-invoice Generate, generate qr-code, generate E-invoice Eway bill,EWAY BILL, E-WAY BILL,E-WAY
        generate E-invoice Eway bill with qr code, generate eway bill invoice, eway bill generate, E-invoice eway bill generate, e-way bill generation,
        e-way bill generation with qr code, e-way bill PDF format, e-way bill PDF format with qr code, generate invoice, Invoice, generate e-way bill, generate eway,
        generate E-invoices, generate, E-Invoice, einvoice, Eway bill,e-way,
    """,
    'live_test_url': 'https://www.youtube.com/watch?v=DlagcTQwIc0',
    'author': 'Geo Technosoft',
    'sequence': 1,
    'website': 'https://www.geotechnosoft.com',
    'depends': ['base', 'sale_management', 'stock', 'purchase', 'contacts','web_notify','l10n_in','account'],
    'data': [
        'security/user_groups.xml',
        'security/ir.model.access.csv',
        'data/uom_mapping.xml',
        'data/uom_data.xml',
        'data/sub_supply_type_data.xml',
        'wizard/vehicle_view.xml',
        'wizard/consolidate_view.xml',
        'wizard/cancel_bill_view.xml',
        'wizard/extend_validity_wizard_view.xml',
        'wizard/update_tax_view.xml',
        'views/eway_configuration_view.xml',
        'views/transporter_view.xml',
        # 'views/unit_quantity_code_view.xml',
        'views/uom_mapping_view.xml',
        'views/uom_uom_views.xml',
        'views/state_view.xml',
        'views/company_view.xml',
        'views/stock_picking_view.xml',
        'views/res_partner_view.xml',
        'views/stock_warehouse.xml',
        'views/response.xml',
        # 'views/transportation_menu.xml',
    ],
    'images': ['static/description/banner.png'],
    'price': 49,
    'currency': 'USD',
    'license': 'OPL-1',
    'installable': True,
    'application': True,
    'application': True,
    'installable': True,
}
